### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by Purg**
Based on recommendation from github community insights.

### CODE REVIEW

**Review by brianhhu — APPROVED** [review]
LGTM, did we cross-reference any other Kitware-based Code of Conducts to see if they added anything extra besides changing the contact info? Thanks!

**Comment by Purg** [comment]
> LGTM, did we cross-reference any other Kitware-based Code of Conducts to see if they added anything extra besides changing the contact info? Thanks!

I took a relatively quick look through VTK and ParaView and did not see an obvious code of conduct file. I'll ask around a little more to see if something can be propped up.

**Comment by brianhhu** [comment]
Sounds good, don't let this be a blocker as it looks good and merge-able on my end.

**Comment by Purg** [comment]
Given a discussion on a out-of-thread channel, we should hold off on providing a code of conduct for now.

**Pull request closed without merging**
